### PR TITLE
Linolcon Creek AD Initial Setup - Internalfyre

### PR DESCRIPTION
**Pull request by jbeck1563**
Added some field waypoints and more folder organization.

### CODE REVIEW

**Review by Dylan-M — COMMENTED** [review]
One quick change (I need to do it on Lukah's Island too)
The map link needs redone this way:
`[Lincoln Creek by MRG Mapping](the actual link here)`

**Comment by jbeck1563** [comment]
> 
> 
> One quick change (I need to do it on Lukah's Island too)
> The map link needs redone this way:
> `[Lincoln Creek by MRG Mapping](the actual link here)`

Changed to specified formatting.

**Review by Dylan-M — DISMISSED** [review]

**Review by Dylan-M — COMMENTED** [review]
Just noticed you forgot to add yourself to the contributors section in the main readme. You'll want to do that too before I merge.

**Comment by jbeck1563** [comment]
> 
> 
> Just noticed you forgot to add yourself to the contributors section in the main readme. You'll want to do that too before I merge.

- Added proper contrib formatting, changed further descriptions within readme.
- Added more waypoints in autodrive file.

**Review by Dylan-M — COMMENTED** [review]
Need to put 2 spaces at the end of my entry in contributors to force a newline. Then you need to put your link in parens to make it work.

**Comment by jbeck1563** [comment]
> 
> 
> Need to put 2 spaces at the end of my entry in contributors to force a newline. Then you need to put your link in parens to make it work.

Corrected, hopefully.

**Review by Dylan-M — DISMISSED** [review]

**Comment by jbeck1563** [comment]
99% of fields finished up. Opened for review.

**Review by Dylan-M — CHANGES_REQUESTED** [review]
Farm 2 is missing.
Sale points Dairy and NHC Harvesting are in the Farms category
One way road outside the store is set as a 2 way road into oncoming traffic. See: https://imgur.com/vSWiydS

**Comment by Dylan-M** [comment]
Additional crash by driving wrong way on a one way:
https://imgur.com/kt1Q7d4

And the reason why one should be doing one way routes even when there is no traffic (2 of my 3 tractors found each other head on):
https://imgur.com/RcOh41b

**Comment by Dylan-M** [comment]
Dirt road where my tractors had a head on, is actually wide enough for 2 lane traffic.

**Comment by Dylan-M** [comment]
If all 3 points at Borden's are functional, then all 3 should be on the network.

**Comment by Dylan-M** [comment]
Wet Distillers cannot be reached from Borden Dairy.
Same with Valero Renewables.

**Comment by Dylan-M** [comment]
NHC Harvesting is not connected on both ends, requiring a weird and painful turn around on the route that one came in on.
https://imgur.com/hXFY8IN

**Comment by Dylan-M** [comment]
Suggestion: In the settings, set detour capability to 100m

**Pull request closed without merging**
